name: dlox
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  logging: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
